#!/usr/bin/env python

PKG = "kobuki_node"

import re
import sys
import unittest
import xml.etree.ElementTree as ET

PATTERN = r"\$\(find ([^)]+)\)"

launch_file = None

class TestBugWitness(unittest.TestCase):
    def test_bug_witness(self):
        tree = ET.parse(launch_file)
        root = tree.root()
        for rosparam in root.iter("rosparam"):
            if "file" in rosparam.attrib:
                result = re.search(PATTERN, rosparam.attrib["file"])
                if not result is None:
                    self.assertNotIn("turtlebot", result.group(1),
                            "Kobuki launch file depends on Turtlebot.")

if __name__ == '__main__':
    import rostest
    launch_file = sys.argv[1]
    rostest.rosrun(PKG, 'test_bug_witness', TestBugWitness)
